### ISSUE TITLE
[SPIKE] Gather information on current and potential design trends

### ISSUE THREAD

**Issue by LionOnTheWeb** [LionOnTheWeb/lionontheweb-web#38]
# Overview
Having a reference for what design trends are currently relevant, or could be the next big trend, will directly influence the determined aesthetic of the project. The website needs to be attractive and relevant.

# Tasks
- [x] List references to current and potential design trends

**Comment by LionOnTheWeb** [comment]
[Envato - Graphic Design Trends 2023](https://www.youtube.com/watch?v=JeuipCti5ak)
* Anti-branding/Minimalism
    * Maximising use of white-space, focusing on message
* Mixed fonts
    * Mixed use of font capitalization
    * Mixed use of serif and sans-serif
*  3D text
* Retro/Retro-pop design
   * Metalic textured text
   * Saturated colors
   * High contrast colors
   * Nostalgia/Y2K aesthetic
*  Multi-colored blends/gradients (Radiant Gradient)
* Vivid Minimalism
   * Minimal design elements and bright retro colors
* AI Design
* Organic shapes

![Image](https://user-images.githubusercontent.com/38708680/210282725-5d0e62c7-e849-4e2a-8c75-82cef33ed740.png)
![Image](https://user-images.githubusercontent.com/38708680/210283203-b206066a-678b-4d41-9a16-d69252562202.png)
![Image](https://user-images.githubusercontent.com/38708680/210283204-30d586c3-e0c4-4192-a5f1-221c22f550b1.png)
![Image](https://user-images.githubusercontent.com/38708680/210283210-064a414d-4da6-4643-895d-a532d228f558.png)
![Image](https://user-images.githubusercontent.com/38708680/210283208-77bb6039-7ca2-4373-99ff-062f8bb29aee.png)
![Image](https://user-images.githubusercontent.com/38708680/210283209-2aad13d8-0221-4b0b-bc4b-de1e2ed0b92f.png)
![Image](https://user-images.githubusercontent.com/38708680/210283205-3c079616-239e-4c1c-a032-9c98b2d9e65c.png)
![Image](https://user-images.githubusercontent.com/38708680/210283206-5289272e-240d-4380-9e7f-a38b1ebecec1.png)
![Image](https://user-images.githubusercontent.com/38708680/210283207-c082dd97-a97f-44fc-808b-ae722c26d3bf.png)

**Comment by LionOnTheWeb** [comment]
[Phillip VanDusen - 2023 Design Trends](https://www.youtube.com/watch?v=ZMWwwgEYjek)

1. SYSTEMATIC
2. MIDJOURNEY + AI
3. COLLAGE
4. HOLO-MORPH
5. MILITARY INSPIRED
6. DARK MODE TYPOGRAPHY
7. NEU-BRUTALISM
8. 70’S TYPOGRAPHY
9. LENSA-TION
10. GEO-SIMPLICITY
11. CYBER WAVE
12. THE BLOB
13. VAPORWAVE 3.0
14. GLOBAL VOICE
15. VIVA MAGENTA


![Image](https://user-images.githubusercontent.com/38708680/210283540-1085a9e5-6b9d-4e7b-856b-dfddc1a7f195.png)
![Image](https://user-images.githubusercontent.com/38708680/210283539-a1591903-80d9-4096-8a27-2439ee95c1aa.png)
![Image](https://user-images.githubusercontent.com/38708680/210283537-d048bf40-2347-49ba-8adc-f37d4e346770.png)
![Image](https://user-images.githubusercontent.com/38708680/210283536-1a7e86e5-ec3c-44f1-832b-527d4fe5ac38.png)
![Image](https://user-images.githubusercontent.com/38708680/210283538-f922c7da-de4c-4537-9c5d-9b416b0ab9a8.png)
![Image](https://user-images.githubusercontent.com/38708680/210283541-ee1d29b7-c52f-45e4-ae5a-8c4043b1893e.png)
![Image](https://user-images.githubusercontent.com/38708680/210283535-d29fa6a9-563e-44b9-a170-9b1f64a6fdef.png)

**Comment by LionOnTheWeb** [comment]
[DesignSense Web Design Trends of 2023](https://www.youtube.com/watch?v=jbMrZScik_U)

* Immersive 3D Worlds
* Overstimulation
* Scrapbook Aesthetic
* Micro-animation
* Neo-Brutalism
* Smart Video
* Typographic Layouts
* Animated Product Reveals
* Blending Photos with Graphical Elements
* Parallax Scrolling

**Comment by Reaper-X** [comment]
That's some pretty awesome suggestions dude!
